name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-v1-

      - name: Build Open edX Base
        run: |
          docker buildx build . \
            --file .github/build/Dockerfile \
            --target base \
            --build-arg EDX_PLATFORM_VERSION=${GITHUB_SHA} \
            --tag ghcr.io/open-uchile/edx-platform:${GITHUB_SHA} \
            --tag ghcr.io/open-uchile/edx-platform:koa \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache-new" \
            --output "type=docker,push=false"
            
      - name: Build Open edX Testing version
        run: |
          docker buildx build . \
            --file .github/build/Dockerfile \
            --target testing \
            --build-arg EDX_PLATFORM_VERSION=${GITHUB_SHA} \
            --tag ghcr.io/open-uchile/edx-platform:testing-koa \
            --cache-from "type=local,src=/tmp/.buildx-cache-new" \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --output "type=docker,push=false"
      
      - name: Test eol changes
        run: |
          cd .github/test
          docker-compose run cms /openedx/edx-platform/.github/test/tests_cms.sh cms/djangoapps/contentstore/views/tests/test_videos.py && docker-compose down -v

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: open-eol
          password: ${{ secrets.CR_PAT }}

      - name: Push to koa
        if: github.ref == 'refs/heads/openuchile/koa.master'
        run: |
          docker push ghcr.io/open-uchile/edx-platform:${GITHUB_SHA}
          docker push ghcr.io/open-uchile/edx-platform:koa
          docker push ghcr.io/open-uchile/edx-platform:testing-koa

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
